name: Build Framework

on: pull_request

jobs:
  tests:
    name: Build Framework
    runs-on: macos-13
    env: 
       DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v3
    - name: Build framework
      run: make framework
