name: Tests

on: pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: macos-13
    env: 
       DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v3
    - name: Build and run tests
      run: make test
