name: Danger

on: pull_request
    
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  danger:
    name: Run Danger    
    runs-on: macos-13
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 40
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Resolve SwiftPM dependencies
      run: rm -rf ".build" && swift package clean && swift package resolve
    - name: Run build script
      run: gem install bundler && bundle install && bundle exec danger --fail-on-errors=true
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
